name: Gitpod Workspace on New Branch

on:
  push:
    branches:
      - "dev/**"

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        id: check_branch
        run: |
          if [[ $GITHUB_REF == refs/heads/dev/** ]]; then
            echo "Valid branch. Proceeding with workflow."
          else
            echo "Branch does not match 'dev/**'. Exiting workflow."
            exit 78 # Exiting with a neutral status, but GitHub Actions might not support neutral status exits anymore. Adjust as necessary.
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gitpod CLI
        run: |
          wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
          chmod +x gitpod
          ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}

      - name: Create a Gitpod workspace for the new branch
        id: create_workspace
        run: |
          branchName=${GITHUB_REF#refs/heads/}
          repoFullName=${{ github.repository }}
          WORKSPACE_URL=$(./gitpod ws create github.com/$repoFullName/tree/$branchName --dont-wait)
          echo "WORKSPACE_URL=$WORKSPACE_URL" >> $GITHUB_ENV
          echo "::set-output name=workspace_url::$WORKSPACE_URL"
